# Use a full python image instead of slim for better compatibility
FROM python:3.9-buster

# Update and install system dependencies with a fix for "Exit Code 100"
RUN apt-get update --fix-missing && apt-get install -y \
    libzbar0 \
    libgl1-mesa-glx \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy requirements and install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the code
COPY . .

# Use the PORT environment variable provided by Render
CMD uvicorn main:app --host 0.0.0.0 --port $PORT