# Use the official Python image
FROM python:3.9-slim

# Install system dependencies for pyzbar and Pillow
RUN apt-get update && apt-get install -y \
    libzbar0 \
    libgl1-mesa-glx \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Copy requirements and install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the code
COPY . .

# Start the application
CMD uvicorn main:app --host 0.0.0.0 --port $PORT